services:
  - type: web
    name: nano-spark-lms
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: base64:5mqffIXKfmg6eSPA0URbWGK9Yoq3AXzAcv02HUQ+K48=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_PORT
        value: "5432"
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array
      - key: LOG_CHANNEL
        value: stderr
